### ISSUE TITLE
Background page text edits

### ISSUE THREAD

**Issue by karindalziel** [CDRH/austen#39]
All these edits are to the background text itself. Possibly have Sara make them?

![fullsizerender-4](https://cloud.githubusercontent.com/assets/284315/11218922/44350aea-8d1d-11e5-8d90-4bf2a1000e51.jpg)

**Comment by karindalziel** [comment]
re: #5, we will link to Carmen's PDF, assuming we have it/can get it.

**Comment by karindalziel** [comment]
Server is rosie.unl.edu

The path once you log into the server is /var/www/rails/austen/app/views/background/index.html.erb

**Comment by karindalziel** [comment]
For #5, comment out rather than deleting, we'll add it in again later.

**Comment by sduke** [comment]
@karindalziel So I got everything done except the hanging indents portion. How would I create the  hanging indents?
