### ISSUE TITLE
Interface changes to selection of word frequencies

### ISSUE THREAD

**Issue by karindalziel** [CDRH/austen#42]
Right now it goes Characters/Character Type/Sex/Indirect Diction. 

The new order will be: 

Character  Direct Speech
------------
Include Narrator in this section as a regular character. Sort Alphabetically.

Character Indirect Diction
--------------------
collapse all "character x as character y" characters into "Character x indirect diction". "Narrator as Character x" entries should stay the same. Narrator as character should go first, otherwise sort alphabetically. Possibly make these smaller? (play around with interface and size)

Traits
--------
All traits will follow

Add a section for "all novels" which will include combined traits. will talk about with @jduss4 and Brian. See issue #41

**Comment by karindalziel** [comment]
Changed this to the following because of the way Jessica's script works. Need to check with Laura White to see if this is correct

* Character Direct Speech
* Character Indirect Diction
* Trait: Character Type
* Trait: Character Sex
* Trait: Character Marriage Status
* Trait: Character Class Status
* Trait: Character Age
* Trait: Character Occupation

**Comment by laurawhite4** [comment]
Yes, these are correct.  Thanks--
