### ISSUE TITLE
Word Frequency interface

### ISSUE THREAD

**Issue by karindalziel** [CDRH/austen#52]
Need button for choosing direct/indirect/FID for all—claims in Background only make sense with this capacity—frequency tables just show unique for direct speech (We changed how this was to be done, Karin needs to find her notes?)

**Comment by karindalziel** [comment]
I think we fixed this with the labels, will need to double check with Laura White to be sure.

**Comment by laurawhite4** [comment]
Great—will check as part of the big edit.

Best,

Laura

**Comment by karindalziel** [comment]
We changed how this works by adding "Character Direct Speech" and "Character Indirect Diction"
