### ISSUE TITLE
Proper names showing up uncapitalized

### ISSUE THREAD

**Issue by karindalziel** [CDRH/austen#54]
Put in note about proper names showing up in the results uncapitalized. (May need to edit XML)

**Comment by karindalziel** [comment]
First Step: Check against XML

**Comment by sduke** [comment]
##### Sense and Sensibility
Mrs Jennings - should be "Mrs. Jennings" (#aus.004.jenn)
Mr Robert Ferrars - should be "Mr. Robert Ferrars" (#aus.004.rob)

##### Persuasion
Speaking together Mr. Charles Musgrove , Miss Henrietta Musgrove and Captain Frederick - unnecessary space after "Mr. Charles Musgrove," (#aus.002.charhenrwent)
Speaking together Mrs. Musgrove , Mr. Musgrove and Henrietta Musgrove - unnecessary space after "Mrs. Musgrove," (#aus.002.mrsmusmrmushenr)
Speaking together Sir Walter Elliot , Miss Elizabeth Elliot and Mrs Penelope Clay - unnecessary space after "Sir Walter Elliot," also should be "Mrs. Penelope Clay" (#aus.002.sirwaltelizclay)

##### Mansfield Park
Mansfield Park society - should this be "Mansfield Park Society" as a title? (#aus.006.mpsoc)
Newspaper (#aus.006.news)

This should be all of the errors.

**Comment by laurawhite4** [comment]
Hi, Stephanie—

Mansfield Park society should have society lower-case.  All else looks like the right correction.

Thanks—

Laura

**Comment by karindalziel** [comment]
All these will need to be changed in the original files, I'm assigning to @lweakly for now, but it may be done by someone else. Also, remember that carmen has the 001(PP) file right now, so don't edit that one.

**Comment by karindalziel** [comment]
I think this is done
