### ISSUE TITLE
Changes to the Character Direct Speech box

### ISSUE THREAD

**Issue by karindalziel** [CDRH/austen#62]
1: Narrators should be at the top
2: All characters should have an initial capital letter
3: All characters should be alphabetized after the narrator (currently, the alphabetization seems to be placing the non capitalized people at the bottom)

![screen shot 2016-02-03 at 11 45 31 am](https://cloud.githubusercontent.com/assets/284315/12791600/78ff5130-ca6d-11e5-9b55-77f1fb9a5782.png)

Replaces Issues #59 & #56 

Wait until Karin has met with Brian - should ordering go in Brian's script, Jessica's script, or TEI file?

**Comment by jduss4** [comment]
All of these are done except for the capitalization of only the first letter.  This one might need some revisiting.  Because I didn't want to make assumptions about people's names, I didn't want to capitalize anything *except* the first letter, so now there are labels like "A young Lucas boy"

**Comment by laurawhite4** [comment]
That sounds right, Jessica—

Laura

**Comment by karindalziel** [comment]
Gonna call this done
